// Isolated Electron acceptance run. No player profile or progress is modified.
const {_electron}=require('/home/djabo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');const assert=require('node:assert/strict');const root='/home/djabo/Downloads/Void Sun';
(async()=>{let app;try{
 const profile='/tmp/voidsun-model-qa';fs.mkdirSync(profile,{recursive:true});fs.writeFileSync(profile+'/janela.json',JSON.stringify({mode:'windowed',width:1440,height:900,zoom:process.env.VOIDSUN_QA_ZOOM?Number(process.env.VOIDSUN_QA_ZOOM):1}));
 const env=Object.fromEntries(Object.entries({...process.env,DISPLAY:process.env.DISPLAY||':0',VOIDSUN_DATA:profile}).filter(([k])=>k!=='FORGE_DEV_URL'));
 const packed=process.env.VOIDSUN_QA_PACKED==='1';app=await _electron.launch({executablePath:packed?root+'/Void Sun':root+'/node_modules/electron/dist/electron',args:['--ozone-platform=x11','--disable-features=Vulkan','--no-sandbox',...(packed?[]:[root])],env,timeout:30000});
 const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.waitForTimeout(6200);
 for(let i=0;i<4;i++){for(const name of ['Próxima página','Entendido!','Pular tutorial']){const b=page.getByRole('button',{name,exact:true});if(await b.isVisible().catch(()=>false))await b.click({force:true});}await page.waitForTimeout(200);}
 if(packed)await page.getByRole('button',{name:/Amostra visual 3D/}).click();else await page.evaluate(()=>location.hash='#/amostra-3d');
 await page.waitForSelector('[data-sample-ready=true]',{timeout:30000});await page.waitForTimeout(1200);
 const snap=async()=>JSON.parse(await page.locator('output[data-arena-snapshot]').getAttribute('data-arena-snapshot'));
 const capture=async(name)=>{const b64=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));fs.writeFileSync('/tmp/'+name+'.png',Buffer.from(b64,'base64'));};
 await capture('voidsun-v2-scene');await page.getByRole('button',{name:'Modelos e equipamentos'}).click();await page.getByRole('button',{name:'Ver personagem de perto'}).click();await page.waitForTimeout(1300);await capture('voidsun-v2-model');
 await page.getByLabel('Mostrar itens equipados',{exact:true}).check();await page.getByLabel('Elmo',{exact:true}).check();await page.getByLabel('Escudo',{exact:true}).check();await page.waitForTimeout(500);await capture('voidsun-v2-armor');await page.getByRole('button',{name:'Testar golpe',exact:true}).click();await page.waitForTimeout(450);await capture('voidsun-v2-strike');await page.waitForTimeout(650);
 for(const body of ['male-normal','female-normal','male-strong','female-strong']){await page.locator('.workshop select').nth(1).selectOption(body);await page.waitForTimeout(350);assert.equal((await snap()).models[0].body,body);await capture('voidsun-v2-'+body);}
 await page.getByLabel('Elmo',{exact:true}).uncheck();await page.locator('.workshop select').nth(2).selectOption('braid');await page.waitForTimeout(500);await capture('voidsun-v2-braid');await page.locator('.workshop select').nth(2).selectOption('ponytail');await page.waitForTimeout(350);await capture('voidsun-v2-pony');
 await page.getByRole('button',{name:'Fechar oficina'}).click();await page.getByRole('button',{name:'Clássica',exact:true}).click();await page.waitForTimeout(1100);
 const canvas=page.locator('.stage canvas');let r=await canvas.boundingBox(),s=await snap();const before=s.actors.map(a=>a.slot);
 await page.mouse.move(r.x+r.width*.8,r.y+r.height*.75);await page.mouse.down();await page.mouse.move(r.x+r.width*.8+80,r.y+r.height*.75+15,{steps:12});await page.mouse.up();await page.waitForTimeout(500);s=await snap();assert.notEqual(s.orbit.yaw,0);assert.deepEqual(s.actors.map(a=>a.slot),before);
 const initialZoom=s.orbit.zoom;await page.mouse.wheel(0,-120);await page.waitForTimeout(600);assert.ok((await snap()).orbit.zoom>initialZoom);
 await page.getByRole('button',{name:'Isométrica',exact:true}).click();await page.waitForTimeout(900);await page.getByRole('button',{name:'Mover Brunhild',exact:false}).click();s=await snap();r=await canvas.boundingBox();const slot=s.slots.find(t=>t.id==='player-front-2');await page.mouse.click(r.x+slot.x*r.width,r.y+slot.y*r.height);await page.waitForTimeout(1300);s=await snap();assert.equal(s.actors[0].slot,'player-front-2');assert.equal(s.actors[0].moving,false);
 await page.getByRole('button',{name:'Brasa do Vazio',exact:false}).click();s=await snap();await page.mouse.click(r.x+s.crate.x*r.width,r.y+s.crate.y*r.height);await page.waitForTimeout(1150);s=await snap();assert.equal(s.crate.alive,false);assert.ok(s.particles>10);await capture('voidsun-v2-impact');await page.waitForTimeout(3400);assert.equal((await snap()).particles,0);await page.getByRole('button',{name:'Restaurar caixa',exact:false}).click();await page.waitForTimeout(300);assert.equal((await snap()).crate.alive,true);
 await page.getByRole('button',{name:'Lança de Geada',exact:false}).click();s=await snap();await page.mouse.click(r.x+s.crate.x*r.width,r.y+s.crate.y*r.height);await page.waitForTimeout(1150);assert.equal((await snap()).crate.alive,false);await page.waitForTimeout(3400);assert.equal((await snap()).particles,0);
 await page.getByLabel('Testar personagens 3D',{exact:true}).uncheck();await page.waitForTimeout(350);await capture('voidsun-v2-sprites');await page.getByLabel('Testar personagens 3D',{exact:true}).check();
 const stats=await snap();assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync('/tmp/voidsun-v2-qa-results.json',JSON.stringify({packed,errors,stats},null,2));console.log(JSON.stringify({packed,errors,stats}));
 await page.getByRole('button',{name:'Batalha',exact:true}).click();await page.waitForSelector('.sample .stage canvas',{state:'detached',timeout:5000});
 }finally{await app?.close();}})().catch(e=>{console.error(e);process.exitCode=1});
