import {describe,it,expect} from 'vitest';
import * as T from 'three';
import {ArenaOrbit} from '../src/ui/sample3d/orbit';
class Surface extends EventTarget {style={touchAction:'',cursor:''};captured=new Set<number>();setPointerCapture(id:number){this.captured.add(id);}hasPointerCapture(id:number){return this.captured.has(id);}releasePointerCapture(id:number){this.captured.delete(id);}}
function setup(){const canvas=new Surface(),camera=new T.OrthographicCamera();let clicks=0;const orbit=new ArenaOrbit(canvas as unknown as HTMLCanvasElement,camera,()=>clicks++,()=>{});orbit.resize(1600,900);orbit.update(1);return {canvas,camera,orbit,get clicks(){return clicks;}};}
function pointer(c:Surface,type:string,id:number,x:number,y:number){const e=new Event(type);Object.assign(e,{pointerId:id,clientX:x,clientY:y,button:0});c.dispatchEvent(e);}
describe('Camera gestures do not issue battle actions',()=>{
 it('clicks once for a tap; a drag and multi-touch never click',()=>{const s=setup();try{pointer(s.canvas,'pointerdown',1,30,40);pointer(s.canvas,'pointerup',1,30,40);expect(s.clicks).toBe(1);pointer(s.canvas,'pointerdown',1,30,40);pointer(s.canvas,'pointermove',1,130,60);pointer(s.canvas,'pointerup',1,130,60);expect(s.clicks).toBe(1);pointer(s.canvas,'pointerdown',1,30,40);pointer(s.canvas,'pointerdown',2,130,40);pointer(s.canvas,'pointermove',2,230,40);pointer(s.canvas,'pointerup',2,230,40);pointer(s.canvas,'pointerup',1,30,40);expect(s.clicks).toBe(1);}finally{s.orbit.dispose();}});
 it('rotates continuously and interpolates presets without teleporting',()=>{const s=setup();try{const initial=s.orbit.snapshot().yaw;s.orbit.rotate(.38);s.orbit.update(.016);expect(s.orbit.snapshot().yaw).toBeGreaterThan(initial);expect(s.orbit.snapshot().yaw).toBeLessThan(initial+.38);for(let i=0;i<100;i++)s.orbit.update(.016);expect(s.orbit.snapshot().yaw).toBeCloseTo(initial+.38,5);s.orbit.preset('classic');s.orbit.update(1);expect(s.orbit.snapshot().yaw).toBeCloseTo(0,4);}finally{s.orbit.dispose();}});
 it('zooms with pinch and enforces near/far limits',()=>{const s=setup();try{pointer(s.canvas,'pointerdown',1,0,0);pointer(s.canvas,'pointerdown',2,100,0);pointer(s.canvas,'pointermove',2,200,0);s.orbit.update(1);expect(s.orbit.zoom).toBeCloseTo(2.46,4);s.orbit.zoomBy(100);s.orbit.update(1);expect(s.orbit.zoom).toBeCloseTo(6.5,4);s.orbit.zoomBy(.0001);s.orbit.update(1);expect(s.orbit.zoom).toBeCloseTo(.65,4);}finally{s.orbit.dispose();}});
 it('cancels interrupted gestures and detaches inputs on exit',()=>{const s=setup();pointer(s.canvas,'pointerdown',1,0,0);pointer(s.canvas,'pointercancel',1,0,0);pointer(s.canvas,'pointerup',1,0,0);expect(s.clicks).toBe(0);s.orbit.dispose();pointer(s.canvas,'pointerdown',1,0,0);pointer(s.canvas,'pointerup',1,0,0);expect(s.clicks).toBe(0);expect(s.canvas.captured.size).toBe(0);});
});
