/**
 * Quais símbolos existem e para que servem. Os desenhos vêm de game-icons.net
 * (game-icons.ts); aqui ficam os nomes em português, as cores padrão e as
 * opções por uso (custo de cada recurso, classe de cada deck, ATK, DEF).
 */
import type { ColorId, ResourceId } from '../../model/types';
import { CHOICES, ICONS } from './game-icons';

export { ICONS };

/** Nome legível de cada símbolo (interface). */
export const ICON_NAMES: Record<string, string> = {
  'mailed-fist': 'Manopla', fist: 'Punho', 'heart-beats': 'Coração pulsante',
  'small-fire': 'Chama', 'burning-embers': 'Brasas', 'flame-spin': 'Espiral de fogo',
  'floating-crystal': 'Cristal flutuante', 'crystal-growth': 'Drusa de cristal', crystalize: 'Gota cristalina', 'crystal-shine': 'Cristal radiante',
  'linden-leaf': 'Folha', 'oak-leaf': 'Folha de carvalho', sprout: 'Broto', 'vine-leaf': 'Folha de videira',
  spectre: 'Espectro', soul: 'Alma', 'soul-vessel': 'Receptáculo de alma',
  moon: 'Lua', hood: 'Capuz', 'concentric-crescents': 'Crescentes',
  sun: 'Sol', 'heraldic-sun': 'Sol heráldico', 'holy-symbol': 'Símbolo sagrado', 'holy-grail': 'Graal',
  'sheikah-eye': 'Olho místico', 'templar-eye': 'Olho templário', 'all-seeing-eye': 'Olho que tudo vê', meditation: 'Meditação',
  'two-coins': 'Moedas', 'crown-coin': 'Moeda coroada',
  'axe-sword': 'Machado e espada', 'crossed-axes': 'Machados cruzados', 'battle-axe': 'Machado de batalha', 'brutal-helm': 'Elmo brutal', 'swords-emblem': 'Brasão de espadas',
  'spell-book': 'Grimório', 'pointy-hat': 'Chapéu de mago', 'wizard-staff': 'Cajado', 'crystal-ball': 'Bola de cristal', 'book-aura': 'Livro arcano',
  'stag-head': 'Cervo', oak: 'Carvalho', 'holy-oak': 'Carvalho sagrado', 'wolf-head': 'Lobo', 'bow-arrow': 'Arco e flecha',
  'dread-skull': 'Caveira sinistra', 'horned-skull': 'Caveira chifruda', 'skull-staff': 'Cajado de caveira', 'pentagram-rose': 'Pentagrama', 'crowned-skull': 'Caveira coroada',
  'cloak-dagger': 'Capa e adaga', 'sacrificial-dagger': 'Adaga ritual', 'hooded-assassin': 'Assassino', 'dagger-rose': 'Adaga e rosa',
  'templar-shield': 'Escudo templário', 'jeweled-chalice': 'Cálice', 'winged-scepter': 'Cetro alado', 'angel-wings': 'Asas de anjo',
  lotus: 'Lótus', lyre: 'Lira', harp: 'Harpa',
  'round-potion': 'Poção', 'health-potion': 'Poção de vida', 'standing-potion': 'Frasco', 'tied-scroll': 'Pergaminho',
  'visored-helm': 'Elmo com viseira', anvil: 'Bigorna', 'spartan-helmet': 'Elmo espartano', 'black-knight-helm': 'Elmo de cavaleiro',
  broadsword: 'Espada larga', 'crossed-swords': 'Espadas cruzadas', 'triple-claws': 'Garras', 'spinning-sword': 'Lâmina giratória', 'claw-slashes': 'Arranhões',
  // coleção ampliada (sóbria, de temática épica)
  'gauntlet': 'Manopla',
  'heart-organ': 'Coração',
  'heart-armor': 'Coração blindado',
  'templar-heart': 'Coração templário',
  'chained-heart': 'Coração acorrentado',
  'pierced-heart': 'Coração trespassado',
  'bleeding-heart': 'Coração sangrando',
  'blood': 'Sangue',
  'lungs': 'Pulmões',
  'thor-fist': 'Punho do trovão',
  'armor-punch': 'Soco blindado',
  'flame': 'Labareda',
  'burning-skull': 'Caveira em chamas',
  'fire-ring': 'Anel de fogo',
  'fire-silhouette': 'Silhueta em chamas',
  'wildfires': 'Incêndio',
  'fire-axe': 'Machado flamejante',
  'flame-claws': 'Garras de fogo',
  'burning-eye': 'Olho em chamas',
  'fire-shrine': 'Altar de fogo',
  'fire-zone': 'Chama viva',
  'fire-breath': 'Sopro de fogo',
  'crystal-cluster': 'Estrela de cristal',
  'rune-stone': 'Pedra rúnica',
  'crystal-eye': 'Olho de cristal',
  'crystal-wand': 'Varinha de cristal',
  'magic-swirl': 'Espiral arcana',
  'triorb': 'Três orbes',
  'concentration-orb': 'Orbe de concentração',
  'unstable-orb': 'Orbe instável',
  'vortex': 'Vórtice',
  'gems': 'Gemas',
  'prism': 'Prisma',
  'magic-portal': 'Fenda mágica',
  'orbital': 'Órbita',
  'comet-spark': 'Cometa',
  'heavy-thorny-triskelion': 'Tríscele de espinhos',
  'tree-roots': 'Raízes',
  'acorn': 'Bolota',
  'maple-leaf': 'Folha de bordo',
  'falling-leaf': 'Folha caindo',
  'thorny-vine': 'Espinheiro',
  'curling-vines': 'Trepadeiras',
  'plant-roots': 'Broto e raízes',
  'pine-tree': 'Pinheiro',
  'leaf-swirl': 'Redemoinho de folhas',
  'thorn-helix': 'Hélice de espinhos',
  'light-thorny-triskelion': 'Tríscele de ramos',
  'willow-tree': 'Salgueiro',
  'evil-tree': 'Árvore sinistra',
  'ginkgo-leaf': 'Folha de ginkgo',
  'death-skull': 'Caveira',
  'grim-reaper': 'Ceifador',
  'reaper-scythe': 'Foice e caveira',
  'tombstone': 'Lápide',
  'coffin': 'Caixão',
  'haunting': 'Assombração',
  'skull-in-jar': 'Caveira no frasco',
  'candle-skull': 'Vela e caveira',
  'crossed-bones': 'Ossos cruzados',
  'spark-spirit': 'Espírito',
  'daemon-skull': 'Caveira demoníaca',
  'skull-signet': 'Anel de caveira',
  'eclipse': 'Eclipse',
  'nested-eclipses': 'Eclipses',
  'spiky-eclipse': 'Eclipse espinhoso',
  'moon-bats': 'Lua e morcegos',
  'raven': 'Corvo',
  'crow-dive': 'Corvo mergulhando',
  'hooded-figure': 'Vulto encapuzado',
  'bottled-shadow': 'Sombra no frasco',
  'shadow-grasp': 'Mão da sombra',
  'two-shadows': 'Duas sombras',
  'shadow-follower': 'Sombra que segue',
  'cracked-mask': 'Máscara rachada',
  'wing-cloak': 'Capa de asas',
  'barbed-sun': 'Sol de espinhos',
  'spiked-halo': 'Auréola',
  'ankh': 'Ankh',
  'angel-outfit': 'Anjo',
  'dove': 'Pomba',
  'prayer-beads': 'Rosário',
  'candle-light': 'Vela',
  'chalice-drops': 'Cálice sagrado',
  'pouring-chalice': 'Cálice vertendo',
  'gothic-cross': 'Cruz gótica',
  'jerusalem-cross': 'Cruz de Jerusalém',
  'cross-flare': 'Cruz radiante',
  'sunbeams': 'Raios de sol',
  'holy-water': 'Água benta',
  'winged-emblem': 'Emblema alado',
  'third-eye': 'Terceiro olho',
  'eye-of-horus': 'Olho de Hórus',
  'yin-yang': 'Yin-yang',
  'triple-yin': 'Três yins',
  'aura': 'Aura',
  'beams-aura': 'Aura radiante',
  'overmind': 'Mente superior',
  'spiral-bloom': 'Espiral',
  'octogonal-eye': 'Olho octogonal',
  'surrounded-eye': 'Olho cercado',
  'rear-aura': 'Aura de meditação',
  'divided-spiral': 'Espiral dividida',
  'coins-pile': 'Pilha de moedas',
  'gold-bar': 'Barra de ouro',
  'gold-stack': 'Lingotes',
  'gold-nuggets': 'Pepitas',
  'open-treasure-chest': 'Baú aberto',
  'locked-chest': 'Baú trancado',
  'chest': 'Baú',
  'shiny-purse': 'Bolsa de ouro',
  'imperial-crown': 'Coroa imperial',
  'jewel-crown': 'Coroa de joias',
  'gold-scarab': 'Escaravelho de ouro',
  'horned-helm': 'Elmo de chifres',
  'viking-helmet': 'Elmo viking',
  'warlord-helmet': 'Elmo do senhor da guerra',
  'overlord-helm': 'Elmo do soberano',
  'spartan': 'Hoplita',
  'war-axe': 'Machado de guerra',
  'warhammer': 'Martelo de guerra',
  'two-handed-sword': 'Montante',
  'gladius': 'Gládio',
  'flail': 'Mangual',
  'spiked-mace': 'Maça cravejada',
  'sword-brandish': 'Espada em punho',
  'knight-banner': 'Estandarte',
  'sword-in-stone': 'Espada na pedra',
  'pentacle': 'Pentáculo',
  'black-book': 'Tomo negro',
  'secret-book': 'Livro selado',
  'open-book': 'Livro aberto',
  'book-storm': 'Tempestade arcana',
  'magic-gate': 'Portal arcano',
  'crescent-staff': 'Bastão crescente',
  'lunar-wand': 'Varinha lunar',
  'orb-wand': 'Cetro do orbe',
  'magic-palm': 'Mão arcana',
  'fire-spell-cast': 'Magia de fogo',
  'ice-spell-cast': 'Magia de gelo',
  'bolt-spell-cast': 'Magia de raio',
  'scroll-unfurled': 'Pergaminho',
  'wolf-howl': 'Lobo uivando',
  'direwolf': 'Lobo atroz',
  'bear-head': 'Urso',
  'boar': 'Javali',
  'fox-head': 'Raposa',
  'eagle-head': 'Águia',
  'werewolf': 'Lobisomem',
  'bowman': 'Arqueiro',
  'quiver': 'Aljava',
  'crossbow': 'Besta',
  'barbed-arrow': 'Flecha farpada',
  'broadhead-arrow': 'Ponta de flecha',
  'forest': 'Floresta',
  'circle-forest': 'Bosque',
  'hunter-eyes': 'Olhos na mata',
  'cauldron': 'Caldeirão',
  'raise-zombie': 'Mão da cova',
  'cursed-star': 'Estrela maldita',
  'backstab': 'Punhalada',
  'stiletto': 'Estilete',
  'thrown-daggers': 'Adagas de arremesso',
  'daggers': 'Adagas',
  'plain-dagger': 'Adaga',
  'broad-dagger': 'Adaga larga',
  'curvy-knife': 'Faca curva',
  'knife-thrust': 'Estocada',
  'lockpicks': 'Gazuas',
  'poison-bottle': 'Veneno',
  'domino-mask': 'Máscara',
  'skull-mask': 'Máscara de caveira',
  'rogue': 'Ladino',
  'assassin-pocket': 'Bolso do assassino',
  'winged-shield': 'Escudo alado',
  'griffin-shield': 'Escudo do grifo',
  'cross-shield': 'Escudo da cruz',
  'dragon-shield': 'Escudo do dragão',
  'healing-shield': 'Escudo de cura',
  'crenulated-shield': 'Escudo ameado',
  'round-shield': 'Broquel',
  'winged-sword': 'Espada alada',
  'bird-scepter': 'Cetro da águia',
  'church': 'Igreja',
  'chakram': 'Chakram',
  'lotus-flower': 'Flor de lótus',
  'peace-dove': 'Pomba',
  'gong': 'Gongo',
  'drum': 'Tambor',
  'pan-flute': 'Flauta de Pã',
  'flute': 'Flauta',
  'hunting-horn': 'Trompa de caça',
  'violin': 'Violino',
  'magic-potion': 'Poção mágica',
  'bubbling-flask': 'Frasco borbulhante',
  'round-bottom-flask': 'Balão alquímico',
  'fizzing-flask': 'Frasco efervescente',
  'potion-of-madness': 'Poção da loucura',
  'vial': 'Tubo de ensaio',
  'pestle-mortar': 'Pilão',
  'herbs-bundle': 'Maço de ervas',
  'treasure-map': 'Mapa do tesouro',
  'old-lantern': 'Lanterna',
  'primitive-torch': 'Tocha',
  'skeleton-key': 'Chave mestra',
  'rope-coil': 'Corda',
  'pouch-with-beads': 'Bolsa de contas',
  'powder-bag': 'Saco de pólvora',
  'crested-helmet': 'Elmo de crista',
  'heavy-helm': 'Elmo pesado',
  'breastplate': 'Peitoral',
  'chest-armor': 'Couraça',
  'spiked-armor': 'Armadura de espinhos',
  'layered-armor': 'Armadura de placas',
  'shoulder-armor': 'Ombreiras',
  'greaves': 'Grevas',
  'leg-armor': 'Perneiras',
  'metal-boot': 'Bota de aço',
  'belt-armor': 'Cinturão',
  'intricate-necklace': 'Colar',
  'power-ring': 'Anel de poder',
  'skull-ring': 'Anel de caveira',
  'anvil-impact': 'Bigorna',
  'sword-smithing': 'Forja',
  'blacksmith': 'Ferreiro',
  'rosa-shield': 'Escudo estrelado', 'edged-shield': 'Escudo com cruz', 'heart-shield': 'Escudo com coração', 'viking-shield': 'Escudo redondo', 'bordered-shield': 'Escudo bordado', 'heart-drop': 'Vida',
};

/** Cor padrão do símbolo de cada recurso. */
export const RESOURCE_COLORS: Record<ResourceId, string> = {
  vigor: '#d9563f', fury: '#ff7a1a', mana: '#4a93ff', nature: '#5fb24a', souls: '#a88bff',
  shadow: '#9a6bff', faith: '#f0c850', focus: '#dfe8f5', gold: '#eab83c',
};

export const STEEL = '#d3dae3';

export const resourceChoices = (r: string): string[] => CHOICES[`res:${r}`] ?? [];
export const classChoices = (c: ColorId | string): string[] => CHOICES[`cls:${c}`] ?? CHOICES['cls:gear'];
export const ATK_CHOICES = CHOICES.atk;
export const DEF_CHOICES = CHOICES.def;

/** Símbolo padrão de um recurso, de um deck, do ataque e da defesa. */
export const resourceIcon = (r: string): string | undefined => resourceChoices(r)[0];
export const classIcon = (c: string): string => classChoices(c)[0];
export const ATK_ICON = ATK_CHOICES[0];
export const DEF_ICON = DEF_CHOICES[0];

export const RESOURCE_IDS = Object.keys(RESOURCE_COLORS) as ResourceId[];
export const isResource = (id: string): id is ResourceId => id in RESOURCE_COLORS;
