const {_electron}=require('/home/djabo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const root='/home/djabo/Downloads/Void Sun',out=process.env.DJABO_QA_OUT||'/tmp/djabo-brand-qa';fs.mkdirSync(out,{recursive:true});
(async()=>{let app;try{
 const profile='/tmp/djabo-brand-profile-'+process.pid;fs.mkdirSync(profile,{recursive:true});fs.writeFileSync(profile+'/janela.json',JSON.stringify({mode:'windowed',width:1440,height:900,zoom:1}));
 const packed=process.env.VOIDSUN_QA_PACKED==='1';const env=Object.fromEntries(Object.entries({...process.env,DISPLAY:process.env.DISPLAY||':0',VOIDSUN_DATA:profile}).filter(([k])=>!['FORGE_DEV_URL','ELECTRON_RUN_AS_NODE'].includes(k)));
 app=await _electron.launch({executablePath:packed?root+'/Void Sun':root+'/node_modules/electron/dist/electron',args:['--ozone-platform=x11','--disable-features=Vulkan','--no-sandbox',...(packed?[]:[root])],env});
 const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const capture=async(name)=>{const b=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));fs.writeFileSync(out+'/'+name+'.png',Buffer.from(b,'base64'));};
 await page.waitForSelector('[data-brand-intro].opening');await page.waitForTimeout(950);await capture('inicio');
 await page.evaluate(()=>{localStorage.setItem('voidsun.aviso','1');sessionStorage.setItem('voidsun.aviso.sessao','1');localStorage.setItem('voidsun.tutorial.v1',JSON.stringify({preference:'skipped',steps:{},finished:[],battleStarted:false}));});
 await page.reload();await page.waitForSelector('[data-brand-intro].opening');await page.waitForTimeout(3300);await capture('abertura-automatica');await page.waitForSelector('[data-brand-intro].opening',{state:'detached',timeout:7000});
 await page.getByRole('button',{name:'Abertura Djabo',exact:true}).click({timeout:12000});
 await page.waitForSelector('[data-brand-intro]:not(.opening)');
 const seek=async(t)=>{await page.getByRole('slider').fill(String(t));await page.waitForTimeout(90);};
 await seek(.96);await capture('D-cortado');assert.equal(await page.locator('[data-devil-logo]').getAttribute('opacity'),'0');assert.equal(await page.locator('[data-byline]').getAttribute('opacity'),null);assert.equal(await page.locator('[data-letter="0"]').getAttribute('data-progress'),'0.000');await seek(1.48);assert.ok(Number(await page.locator('[data-letter="0"]').getAttribute('data-progress'))>0);assert.equal(await page.locator('[data-letter="1"]').getAttribute('data-progress'),'0.000');assert.equal(await page.locator('[data-letter="0"]').getAttribute('clip-path'),null);const jOpacity=Number(await page.locator('[data-letter="0"]').getAttribute('opacity'));assert.ok(jOpacity>0&&jOpacity<1);await capture('j-surgindo');await seek(1.62);assert.ok(Number(await page.locator('[data-letter="1"]').getAttribute('data-progress'))>0);assert.equal(await page.locator('[data-letter="2"]').getAttribute('data-progress'),'0.000');await capture('a-surgindo');await seek(1.76);assert.ok(Number(await page.locator('[data-letter="2"]').getAttribute('data-progress'))>0);assert.equal(await page.locator('[data-letter="3"]').getAttribute('data-progress'),'0.000');await capture('b-surgindo');await seek(2.26);for(let i=0;i<4;i++)assert.equal(await page.locator(`[data-letter="${i}"]`).getAttribute('data-progress'),'1.000');assert.equal(await page.locator('[data-devil-logo]').getAttribute('opacity'),'0');await capture('letras-em-sequencia');const logoX=await page.locator('[data-devil-logo]').getAttribute('x');await seek(2.60);assert.ok(Number(await page.locator('[data-devil-logo]').getAttribute('opacity'))>0);assert.ok(Number(await page.locator('[data-devil-logo]').getAttribute('opacity'))<1);assert.equal(await page.locator('[data-devil-logo]').getAttribute('x'),logoX);assert.equal(await page.locator('[data-devil-logo]').getAttribute('transform'),null);assert.ok(Number(await page.locator('[data-devil-logo]').getAttribute('opacity'))<.3);await capture('simbolo-fade');await seek(2.92);assert.ok(Math.abs(Number(await page.locator('[data-devil-logo]').getAttribute('opacity'))-.5)<.01);await capture('simbolo-meio-fade');await seek(4.0);assert.equal(await page.locator('[data-devil-logo]').getAttribute('opacity'),'1');const alpha=await page.evaluate(async()=>{const el=document.querySelector('[data-devil-logo]'),im=new Image();im.src=el.getAttribute('href');await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);return {corners:[[0,0],[im.width-1,0],[0,im.height-1],[im.width-1,im.height-1]].map(([x,y])=>ctx.getImageData(x,y,1,1).data[3]),blend:getComputedStyle(el).mixBlendMode};});assert.deepEqual(alpha.corners,[0,0,0,0]);assert.equal(alpha.blend,'normal');await capture('assinatura');assert.equal(await page.locator('[data-brand-intro] canvas').count(),0);
 const before=await page.locator('[data-brand-intro]').getAttribute('data-time');await page.waitForTimeout(250);assert.equal(await page.locator('[data-brand-intro]').getAttribute('data-time'),before,'seek must pause');
 await page.getByRole('button',{name:'Repetir',exact:true}).click();await page.waitForTimeout(650);assert.ok(Number(await page.locator('[data-brand-intro]').getAttribute('data-time'))<1.4);
 await page.getByRole('button',{name:'Ver sem controles',exact:true}).click();
 if(process.env.DJABO_QA_VIDEO==='1'){
  fs.mkdirSync(out+'/frames',{recursive:true});const style=await page.addStyleTag({content:'.exit-full{visibility:hidden!important}'}),entries=[],started=Date.now();let i=0;
  while(Date.now()-started<6600){const begin=Date.now(),name='frames/'+String(i++).padStart(4,'0');await capture(name);entries.push({name,t:Date.now()-started});await page.waitForTimeout(Math.max(1,67-(Date.now()-begin)));}
  fs.writeFileSync(out+'/frames.ffconcat','ffconcat version 1.0\n'+entries.map((e,i)=>`file '${e.name}.png'\nduration ${((entries[i+1]?.t??e.t+67)-e.t)/1000}\n`).join(''));await style.evaluate(e=>e.remove());
 }else await page.waitForTimeout(4400);
 await capture('cinema');await page.getByRole('button',{name:'Mostrar controles',exact:true}).click();await seek(4.0);
 await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setMinimumSize(320,480);w.webContents.setZoomFactor(1);w.setContentSize(430,900);});await page.waitForTimeout(200);await capture('mobile');assert.equal(await page.evaluate(()=>innerWidth),430);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1440,900));
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'‹ Menu',exact:true}).click();await page.getByRole('button',{name:'Abertura Djabo',exact:true}).click();await page.waitForTimeout(120);assert.equal(Number(await page.locator('[data-brand-intro]').getAttribute('data-time')),4.0);
 await page.getByRole('button',{name:'Repetir',exact:true}).click();await page.waitForTimeout(150);assert.equal(Number(await page.locator('[data-brand-intro]').getAttribute('data-time')),4.0);
 await page.emulateMedia({reducedMotion:'no-preference'});await page.reload();await page.waitForSelector('[data-brand-intro].opening');await page.keyboard.press('Enter');await page.waitForSelector('[data-brand-intro].opening',{state:'detached',timeout:2500});
 assert.equal(errors.length,0,errors.join('\n'));const result={packed,version:await app.evaluate(({app})=>app.getVersion()),errors,checks:['automatic opening','real symbol alpha, no blend trick','static byline','staggered letter fades with slight rightward movement, no clipping','selected symbol fades after name without translation','vector identity','menu replay','pause/seek','full view','mobile layout','reduced motion','keyboard skip']};fs.writeFileSync(out+'/resultado.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }catch(e){console.error(e);process.exitCode=1;if(app)try{const b=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));fs.writeFileSync(out+'/erro.png',Buffer.from(b,'base64'));}catch{}}
 finally{if(app)await app.close().catch(()=>{});}
})();
